runtime: nodejs22

instance_class: F1

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1

env_variables:
  NODE_ENV: "production"
  GCP_PROJECT_ID: "classcharts"
  GCS_BUCKET: "classcharts-attachments"
  GCS_ALLOWED_USERS_PATH: "config/allowed-users.json"
  NEXTAUTH_URL: "https://classcharts.funfairlabs.com"

beta_settings:
  cloud_build_timeout: "900"
