#!/usr/bin/env bash
set -euo pipefail

PROJECT_ID="${GCP_PROJECT_ID:-classcharts}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

fetch_secret() {
  gcloud secrets versions access latest --secret="$1" --project="$PROJECT_ID" 2>/dev/null || echo ""
}

echo "▶ Fetching secrets..."
GOOGLE_CLIENT_ID=$(fetch_secret GOOGLE_CLIENT_ID)
GOOGLE_CLIENT_SECRET=$(fetch_secret GOOGLE_CLIENT_SECRET)
NEXTAUTH_SECRET=$(fetch_secret NEXTAUTH_SECRET)
ADMIN_EMAIL=$(fetch_secret ADMIN_EMAIL)
CC_EMAIL=$(fetch_secret CLASSCHARTS_PARENT1_EMAIL)
CC_PASSWORD=$(fetch_secret CLASSCHARTS_PARENT1_PASSWORD)
PUSHOVER_API_TOKEN=$(fetch_secret PUSHOVER_API_TOKEN)
PUSHOVER_USER_KEY=$(fetch_secret PUSHOVER_USER_KEY)
FIREBASE_API_KEY=$(fetch_secret FIREBASE_API_KEY)
FIREBASE_AUTH_DOMAIN=$(fetch_secret FIREBASE_AUTH_DOMAIN)
FIREBASE_PROJECT_ID=$(fetch_secret FIREBASE_PROJECT_ID)
FIREBASE_STORAGE_BUCKET=$(fetch_secret FIREBASE_STORAGE_BUCKET)
FIREBASE_MESSAGING_SENDER_ID=$(fetch_secret FIREBASE_MESSAGING_SENDER_ID)
FIREBASE_APP_ID=$(fetch_secret FIREBASE_APP_ID)
FIREBASE_VAPID_KEY=$(fetch_secret FIREBASE_VAPID_KEY)
ONESIGNAL_APP_ID=$(fetch_secret ONESIGNAL_APP_ID)
ONESIGNAL_API_KEY=$(fetch_secret ONESIGNAL_API_KEY)

echo "▶ Building shared package..."
cd "$REPO_ROOT/shared"
npm install
npm run build

echo "▶ Copying shared into frontend for App Engine deploy..."
rm -rf "$REPO_ROOT/frontend/vendor/shared"
mkdir -p "$REPO_ROOT/frontend/vendor/shared"
cp -r "$REPO_ROOT/shared/dist"         "$REPO_ROOT/frontend/vendor/shared/dist"
cp    "$REPO_ROOT/shared/package.json"  "$REPO_ROOT/frontend/vendor/shared/package.json"
cp -r "$REPO_ROOT/shared/node_modules" "$REPO_ROOT/frontend/vendor/shared/node_modules"

echo "▶ Updating frontend package.json to point at vendored shared..."
node -e "
const fs = require('fs');
const pkg = JSON.parse(fs.readFileSync('$REPO_ROOT/frontend/package.json'));
pkg.dependencies['@classcharts/shared'] = 'file:./vendor/shared';
pkg.scripts['gcp-build'] = 'cd vendor/shared && npm install --production && cd ../.. && next build';
fs.writeFileSync('$REPO_ROOT/frontend/package.json', JSON.stringify(pkg, null, 2));
"

echo "▶ Writing app.yaml with secrets..."
COMMIT_SHA=${GITHUB_SHA:0:7}
COMMIT_SHA=${COMMIT_SHA:-$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")}
DEPLOYED_AT=$(date -u +"%d/%m/%Y %H:%M:%S GMT")
APP_URL="https://classcharts.funfairlabs.com"

# Overwrite buildInfo.ts so commit SHA and timestamp are baked into the Next.js build
cat > "$REPO_ROOT/frontend/src/lib/buildInfo.ts" << TS
// Auto-generated by infra/deploy-frontend.sh — do not edit manually
export const BUILD_INFO = {
  commitSha: '${COMMIT_SHA}',
  deployedAt: '${DEPLOYED_AT}',
};
TS

cat > "$REPO_ROOT/frontend/app.yaml" << YAML
runtime: nodejs22
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  max_instances: 2
env_variables:
  NODE_ENV: "production"
  GCP_PROJECT_ID: "${PROJECT_ID}"
  GCS_BUCKET: "classcharts-attachments"
  GCS_ALLOWED_USERS_PATH: "config/allowed-users.json"
  NEXTAUTH_URL: "https://classcharts.funfairlabs.com"
  NEXTAUTH_URL_INTERNAL: "https://classcharts.funfairlabs.com"
  GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
  GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
  NEXTAUTH_SECRET: "${NEXTAUTH_SECRET}"
  ADMIN_EMAIL: "${ADMIN_EMAIL}"
  CLASSCHARTS_PARENT1_EMAIL: "${CC_EMAIL}"
  CLASSCHARTS_PARENT1_PASSWORD: "${CC_PASSWORD}"
  PUSHOVER_API_TOKEN: "${PUSHOVER_API_TOKEN}"
  PUSHOVER_USER_KEY: "${PUSHOVER_USER_KEY}"
  NEXT_PUBLIC_FIREBASE_API_KEY: "${FIREBASE_API_KEY}"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "${FIREBASE_AUTH_DOMAIN}"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: "${FIREBASE_PROJECT_ID}"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "${FIREBASE_STORAGE_BUCKET}"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "${FIREBASE_MESSAGING_SENDER_ID}"
  NEXT_PUBLIC_FIREBASE_APP_ID: "${FIREBASE_APP_ID}"
  NEXT_PUBLIC_FIREBASE_VAPID_KEY: "${FIREBASE_VAPID_KEY}"
  NEXT_PUBLIC_ADMIN_EMAIL: "${ADMIN_EMAIL}"
  NEXT_PUBLIC_ONESIGNAL_APP_ID: "${ONESIGNAL_APP_ID}"
  ONESIGNAL_API_KEY: "${ONESIGNAL_API_KEY}"
beta_settings:
  cloud_build_timeout: "900"
YAML

echo "▶ Writing .env.production for Next.js build-time NEXT_PUBLIC vars..."
cat > "$REPO_ROOT/frontend/.env.production" << ENV
NEXT_PUBLIC_FIREBASE_API_KEY=${FIREBASE_API_KEY}
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
NEXT_PUBLIC_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
NEXT_PUBLIC_FIREBASE_APP_ID=${FIREBASE_APP_ID}
NEXT_PUBLIC_FIREBASE_VAPID_KEY=${FIREBASE_VAPID_KEY}
NEXT_PUBLIC_ADMIN_EMAIL=${ADMIN_EMAIL}
NEXT_PUBLIC_ONESIGNAL_APP_ID=${ONESIGNAL_APP_ID}
ONESIGNAL_API_KEY=$(fetch_secret ONESIGNAL_API_KEY)
ONESIGNAL_APP_ID=$(fetch_secret ONESIGNAL_APP_ID)
ENV

echo "▶ Deploying to App Engine..."
cd "$REPO_ROOT/frontend"
gcloud app deploy --quiet --project="$PROJECT_ID"

echo "✅ Frontend deployed to https://${PROJECT_ID}.appspot.com"
